### ISSUE TITLE
Check-in on ticket state

### ISSUE THREAD

**Issue by bendygirl** [Drupal4Gov/Drupal-GovCon-2015#134] opened 2015-07-17 13:53 UTC
- [x] Permission changes
- [x] Build view
- [x] Create flag
- [x] Create rules to set ticket state to "Checked-in" and back to "Completed" to undo
- [x] Style "Check-in" flag as button
- [x] Style first column of view to not be 99% wide -- use second instead?
- [x] Write email template for check-in (or cancel this part)
- [ ] Export everything to features

Attendee manager appears to have no permissions available for checking in attendees.
an admin can change the ticket state to "Checked-in", but can the attendee manager? 

a work around for using COD for the check-in is to print the list and do it manually.

**Comment by timwood** [comment] 2015-07-17 14:01
How do we want to be able to handle this this year?

**Comment by bendygirl** [comment] 2015-07-17 14:28
I'd like to have computers at registration and check folks off this way.   

Next year, we should look into the bar coding so that sponsors can do leads off tags. But that's next year.

**Comment by timwood** [comment] 2015-07-17 14:39
I'll look at the permissions, enable proper perm for ticket management for attendee manager role and create a view that can be used for this purpose.

How's this sound? The view (modeled after the [ticket export view](https://www.drupalgovcon.org/admin/tickets/export)) would list users alpha by last name and include the following fields:
Attendee First Name
Attendee Last Name
Attendee Email
Dietary needs?
Ticket State and type

Filters:
Ticket state (default to "Completed")
Attendee Name (to include first or last with "contains)
Attendee Email

Views Bulk Operations (actions):
"Change Ticket State" (or maybe use a flag + rules to make this more elegant)

Should we list all tickets on one page (might be a server resource/timeout issue) and make filters ajax so we have less calls to the full page?

**Comment by timwood** [comment] 2015-07-17 14:41
Permissions to test:
Administer ticket registration states
View (and edit) all registrations
Last resort: Administer ticket

**Comment by bendygirl** [comment] 2015-07-17 14:50
the view that's there now works well, maybe clone that and make it its own
basic page for just the "attendee manager" to use for checking in folks. It
lets them search by name which is handy. It also has info on the lunch
request (select option not a viewed option) and the option to change the
ticket state. Probably don't need the date created or "operations" or
tshirts, but everything else works.

Of course, if the view you did already used this, just ignore me.

On Fri, Jul 17, 2015 at 10:39 AM, Tim Wood notifications@github.com wrote:

> I'll look at the permissions, enable proper perm for ticket management for
> attendee manager role and create a view that can be used for this purpose.
> 
> How's this sound? The view (modeled after the ticket export view
> https://www.drupalgovcon.org/admin/tickets/export) would list users
> alpha by last name and include the following fields:
> Attendee First Name
> Attendee Last Name
> Attendee Email
> Dietary needs?
> Ticket State and type
> 
> Filters:
> Ticket state (default to "Completed")
> Attendee First Name
> Attendee Last Name
> Attendee Email
> 
> Views Bulk Operations (actions):
> "Change Ticket State" (or maybe use a flag + rules to make this more
> elegant)
> 
> Should we list all tickets on one page (might be a server resource/timeout
> issue) and make filters ajax so we have less calls to the full page?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Drupal4Gov/Drupal-GovCon-2015/issues/134#issuecomment-122296574
> .

## 

Kirsten
http://uniongal.blogspot.com
Join Uniongal on Reddit http://www.reddit.com/r/Uniongal/

**Comment by timwood** [comment] 2015-07-17 14:56
I didn't make anything yet, just discussing here. I think we don't need extra/extraneous filters, so I wasn't going to add Dietary needs as a filter, but is it useful as a visible field when checking in someone? Is there something different that people get on check-in for special lunches?

**Comment by dsheffler** [comment] 2015-07-17 14:58
If we do the same thing as last year, we just had a list of people who needed vegetarian lunches so those of us who needed them didn't have our food taken by other people who just didn't like the other options available.

**Comment by timwood** [comment] 2015-07-17 15:15
So that is more for lunch handout than registration. We should make sure the special lunches get held at registration or an alternate table. Let's use a print out for that.

**Comment by jdearie** [comment] 2015-07-17 15:15
We had the paper lists for check-in last year - and it included dietary restrictions. We just grabbed those same papers when we were separating out the specialty lunches.  

I think we may have confirmed special dietary restrictions on check-in, but it will definitely be useful to have a print out of the names and the lunches they receive...

**Comment by bendygirl** [comment] 2015-07-17 15:19
yes, at registration, Nina and the team will ask if they still need a
special lunch. Then, they pull those lunches out for the attendees. This
will mostly be for the gluten free bunch this year. But we do ask at
registration.

On Fri, Jul 17, 2015 at 10:58 AM, dsheffler notifications@github.com
wrote:

> If we do the same thing as last year, we just had a list of people who
> needed vegetarian lunches so those of us who needed them didn't have our
> food taken by other people who just didn't like the other options available.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Drupal4Gov/Drupal-GovCon-2015/issues/134#issuecomment-122302275
> .

## 

Kirsten
http://uniongal.blogspot.com
Join Uniongal on Reddit http://www.reddit.com/r/Uniongal/

**Comment by timwood** [comment] 2015-07-17 19:55
Changed "Administer ticket registration states" permission on live site to allow "attendee manager" role.

**Comment by timwood** [comment] 2015-07-17 20:14
Nope, that wasn't the right perm. That was for changing/adding/removing ticket STATES. Duh, Tim.

**Comment by timwood** [comment] 2015-07-17 20:15
Gave "attendee manager" role "View all registrations" and "Edit all registrations" perms.

**Comment by jdearie** [comment] 2015-07-17 22:24
Was thinking column order on the /ci view should be:
last name - first name - dietary need - email - org

Also - in addition to checking in, is there a quick way to update dietary need from the same view? or at least provide a link to the individual ticket so we can update meals?

This way we can export the most current dietary needs each day?

**Comment by timwood** [comment] 2015-07-17 23:49
I've changed the order, but put the "Check-in" action column first, with the intent for @jonraedeke to style it as a button and not 99% width (the default for the theme table styling for first column). It felt like too much linked text when it was in a column with or next to "Edit ticket", which I added as well.

I hadn't thought of updating dietary need, for those that might have missed that or had this change since registering, good idea.

**Comment by timwood** [comment] 2015-07-17 23:58
Since I'm using Flag and Rules I can send an email to the attendee on check-in. It could include a thank you and also important info/links. @jdearie @bendygirl Do you think there is value in this email? What about when the wrong user is checked in, I can't really account for that with simple rules. Here's what I have so far for the check-in email template, mostly taken from other rules based email templates we build.

> Hi timwood,
> Thanks for checking into the conference! Have a blast!
> 
> Subscribe to our newsletter:
> http://eepurl.com/bbJASn
> 
> Follow us on social media:
> https://twitter.com/drupalgovcon
> https://plus.google.com/+Drupal4Gov
> https://www.facebook.com/DrupalGovCon
> 
> --  Drupal GovCon team

**Comment by timwood** [comment] 2015-07-18 00:18
Okay, so the view, flag and rules are finished. Check out the view at https://www.drupalgovcon.org/ci. Should be restricted to Admins and attendee manager.

@jonraedeke When you have a chance, can you please style the flag column "Check-in attendee" to be more like a button? You can pull down a copy of the site from production as I didn't do any of this in Features, yet.

BE VERY CAREFUL when working with this view, one click and a user will be checked in and email sent.

**Comment by timwood** [comment] 2015-07-18 03:47
The checkbox looks great, @jonraedeke! But it looks like the Check-in view still has 99% width on the first column. You may need to view as non-admin to style.

<img width="669" alt="screen shot 2015-07-17 at 11 46 16 pm" src="https://cloud.githubusercontent.com/assets/91050/8760232/29fb5278-2cde-11e5-84b1-7b98c2ac7c7b.png">

**Comment by jonraedeke** [comment] 2015-07-18 04:03
@timwood Thanks, should be fixed now.

**Comment by timwood** [comment] 2015-07-18 16:03
@jonraedeke I just tested the check-in checkbox and it works great, but hides the Flag messages associated with the flagging and unflagging action. I could see the top of the text inside the red box when checked. Can you make it so that text shows somewhere near the box as feedback?

**Comment by timwood** [comment] 2015-07-18 16:34
Here's what I ended up with in the email template:

Hi [ticket:field-profile-first] [ticket:field-profile-last],
Thanks for checking into the conference. The next three days are packed with opportunities -- make sure you make the most of them. Make the time to get to know the great people in this community. Say hello to someone you don't know...start a conversation in the hallway. Attend a Birds of a Feather. Visit a booth and ask questions. Sign up to mentor at the mentoring area. We hope you have a blast this year! 

Here are some important links you may want to reference during the conference:

You can always find the most recent information on the conference schedule, rooms and times on our site at:
https://www.drupalgovcon.org/drupal-govcon-2015/schedule

Build or reference your Schedule:
https://www.drupalgovcon.org/drupal-govcon-2015/schedule/mine

Birds of a Feather:
https://www.drupalgovcon.org/drupal-govcon-2015/bofs

Conference layout:
https://www.drupalgovcon.org/drupal-govcon-2015/floor-layouts

Share your notes about the sessions you attend on our Hackpad:
https://drupalgovcon2015.hackpad.com/

Subscribe to our newsletter:
http://eepurl.com/bbJASn

Follow us on social media:
https://twitter.com/drupalgovcon
https://plus.google.com/+Drupal4Gov
https://www.facebook.com/DrupalGovCon

--  [site:name] team

**Comment by timwood** [comment] 2015-07-18 16:52
Done!

**Closed as completed by timwood** 2015-07-18 16:52 UTC
