### ISSUE TITLE
duplicate tickets/registrations

### ISSUE THREAD

**Issue by bendygirl** [Drupal4Gov/Drupal-GovCon-2015#109] opened 2015-06-05 22:15 UTC
there is a growing difference between Tickets https://www.drupalgovcon.org/admin/conference/1/tickets
and registrations https://www.drupalgovcon.org/ticket_registration/manage/1/registrations

currently, the difference is 72 more tickets than registrations. This may be due to a registrant obtaining multiple tickets or selecting a number for their office/friends. Or these may simply mean we have a few duplicates.

**Comment by timwood** [comment] 2015-06-06 21:21
It could also be due to tickets from spammers that were not deleted and do not show up in the list at https://www.drupalgovcon.org/ticket_registration/manage/1/registrations as that list only shows tickets that have a corresponding Drupal account which created them. I believe when cleaning up spam accounts, we didn't delete tickets for a portion of the accounts removed.

**Comment by timwood** [comment] 2015-06-07 20:38
I've deleted 36 tickets from previous spammers. More to come.

**Comment by timwood** [comment] 2015-06-07 20:42
Deleted three more that were created by "austinfin@yahoo.com", a blocked account that I guess we never confirmed as spammer and so never deleted. I've deleted the tickets and account.

**Comment by timwood** [comment] 2015-06-07 20:45
Deleted 20 more tickets not belonging to any user account.

**Comment by timwood** [comment] 2015-06-07 20:47
Delete 14 more tickets not belonging to any user account.

**Comment by timwood** [comment] 2015-06-07 20:48
One more.

**Comment by timwood** [comment] 2015-06-07 21:13
So we've now got a discrepancy, from the two screens in the original issue above, of **two** tickets. I believe these are the two tickets in question:
https://www.drupalgovcon.org/ticket_registration/6716
https://www.drupalgovcon.org/ticket_registration/6601

You can see the "Registrant" for these tickets is "Anonymous", which I believe means the account, that created these tickets, was since deleted. Tim Arnold at BeaconFire-Red created two accounts by accident, one without the "n" in beacon. Looks like we deleted that account and maybe a ticket. Unfortunately, the ticket that remains is not owned by Tim Arnold's remaining account. You can see by going to his user account [tickets tab](https://www.drupalgovcon.org/users/timarnoldbeaconfire-redcom/tickets). I don't see a way in the UI to assign this ticket to Tim Arnold's account. I could probably do it via a DB query, but don't really want to mess with that. The options are:
1. leave this ticket as is, even though it's not attached to Tim's account (this will mean we forever have a discrepancy)
2. delete this ticket and contact Tim Arnold to ask him to log in and request a new ticket.

Not sure what's with the German Moreno one. Is that a spam account we left active for some reason? Or never confirmed?

To explain: the view at https://www.drupalgovcon.org/ticket_registration/manage/1/registrations has a required relationship on ticket registrant (original person requesting the ticket(s)). If an account has been deleted but the associated tickets not, this is when the discrepancy occurs and will increase if we keep deleting accounts but not tickets.

The takeaway here is:

# MAKE SURE TO DELETE TICKETS BEFORE DELETING SPAM ACCOUNTS

**Closed as completed by timwood** 2015-06-07 21:13 UTC
Labels: SPRINT
