### ISSUE TITLE
Unable to set Times

### ISSUE THREAD

**Issue by bendygirl** [Drupal4Gov/Drupal-GovCon-2015#106] opened 2015-05-30 18:01 UTC
Unable to plot sessions due to a bug with times. Times are rendered 4 hours earlier than EST. Times do not show up in Content Type.

Field Collection
https://www.drupalgovcon.org/admin/structure/field-collections/field-event-timeslots/fields

Time slot view
https://www.drupalgovcon.org/admin/structure/views/view/cod_bof_schedule_timeslots/edit

The entity reference points to a view that does not appear to exist.
cod_schedule_timeslot_widget - entity reference

@jdearie @timwood @Nneka

**Comment by bendygirl** [comment] 2015-05-31 15:35
@Nneka I'm on line so if you need help or want to do a join.me, let me know, I'm available, when not cleaning.

**Comment by Nneka** [comment] 2015-05-31 17:05
Was unable to reproduce this issue on my local development environment.  Thought it would be server time, but it seems that the server time is correct.  I don't have ssh access, but I used the datetime page (https://www.drupalgovcon.org/admin/config/regional/date-time/formats/add) and typed in 'M d Y g:i a T' into the date format, and it generated the correct date.   Still investigating.

**Comment by bendygirl** [comment] 2015-05-31 17:07
@Nneka I could add a few times. Not sure that would be helpful, but if you can fix the time issue, then you should be able to see pretty clearly when the added times revert to the actual time.

**Comment by Nneka** [comment] 2015-05-31 17:12
@bendygirl Ok.  Found the module that generates that "Add Time" form.  Its the cod_schedule module.  Looking at the code to debug.

**Comment by timwood** [comment] 2015-06-03 01:27
Looks like the PHP date extension timezone is set to UTC, which may be the cause for the time mismatch. See the Drupal PHPinfo page here (search for 'date.timezone'): https://www.drupalgovcon.org/admin/reports/status/php

The Times entity's "Date and time" field uses "Date's time zone" for "Time zone handling", which as we see above is set to UTC. See here: https://www.drupalgovcon.org/admin/conference/config/times/manage/fields/field_evttime_date

As of now, we cannot change this setting because there is already data in the MySQL table associated with this field (Drupal warns you as such when you try to change it to "Site's time zone" for example.

Looks like we could try two options for changing this php value from UTC. Modify the .htaccess or add ini_set to settings.php. I think in Acquia's environment the settings.php option is more likely to succeed. Here is a good explanation of the ways to set, albeit in reference to WAMP server. https://www.devside.net/wamp-server/setting-the-default-timezone-for-php-to-use
We should probably ask Dave Stoline.

**Comment by bendygirl** [comment] 2015-06-03 01:45
First off, yeah for figuring it out.

And now, to loop in David.

**Comment by timwood** [comment] 2015-06-03 02:08
Looped Dave via email as he's not part of this Git organization so I cannot @ him here.

**Comment by Nneka** [comment] 2015-06-03 13:30
Thanks @timwood .  I don't mind testing the change.  Let me know.

**Comment by unn** [comment] 2015-06-03 13:31
I am everywhere @timwood

**Comment by timwood** [comment] 2015-06-03 13:58
@Nneka What is the date.timezone set to in your local environment where you did the earlier testing? 

@unn ah ha! I guess I just didn't know your username.

**Comment by Nneka** [comment] 2015-06-03 14:06
@timwood It's populated with nothing.  

date.timezone   no value    no value

Using Virtualbox - Ubuntu

**Comment by jonraedeke** [comment] 2015-06-07 01:40
Not sure this is the exact issue:
https://www.drupal.org/node/2346603

**Comment by timwood** [comment] 2015-06-07 02:01
Also relevant issues? 
https://www.drupal.org/node/1703332

**Comment by timwood** [comment] 2015-06-07 02:03
https://www.drupal.org/node/2407607

**Comment by timwood** [comment] 2015-06-07 02:15
@Nneka Did you figure out anything else with this date format issue? Jon and I think the DGC planning team can work through scheduling with the wrong times displayed if needed, but the one place that times display to public users is on the session node page. I'm going to focus on that for now.

**Comment by timwood** [comment] 2015-06-07 02:30
Temporarily we could hide the session time from session node view. @jonraedeke's suggestion

**Comment by timwood** [comment] 2015-06-07 04:57
We think we have a temporary fix/patch which I've uploaded to D.O. here: https://www.drupal.org/node/2407607#comment-9999695

I need to do a little more testing tomorrow before I commit this to our repo.

**Comment by timwood** [comment] 2015-06-07 18:04
I believe this is now resolved in Dev, will be available on the site soon.

**Closed as completed by timwood** 2015-06-07 18:04 UTC
Labels: SPRINT
